import { ApiError } from "./ApiError.js";
import { prisma } from "./prisma.js";

/**
 * Generate Google Meet link code
 * Format: abc-defg-hij (10-12 characters)
 */
export const generateMeetCode = () => {
  const part1 = Math.random().toString(36).substring(2, 5); // 3 chars
  const part2 = Math.random().toString(36).substring(2, 6); // 4 chars
  const part3 = Math.random().toString(36).substring(2, 5); // 3 chars
  return `${part1}-${part2}-${part3}`;
};

/**
 * Generate Google Meet link URL
 * @param {string} code - Meeting code (optional, auto-generated if not provided)
 * @returns {string} Full Google Meet URL
 */
export const generateMeetLink = (code = null) => {
  const meetCode = code || generateMeetCode();
  return `https://meet.google.com/${meetCode}`;
};

/**
 * Auto-generate and save Google Meet link for webinar
 * @param {string} webinarId - Webinar ID
 * @param {boolean} forceRegenerate - Force regenerate even if link exists
 * @returns {Promise<string>} Generated meet link
 */
export const autoGenerateMeetLink = async (webinarId, forceRegenerate = false) => {
  try {
    const webinar = await prisma.webinar.findUnique({
      where: { id: webinarId },
      select: { meetLink: true, autoGeneratedMeet: true },
    });

    if (!webinar) {
      throw new ApiError(404, "Webinar not found");
    }

    // If link exists and not forcing regeneration, return existing
    if (webinar.meetLink && !forceRegenerate) {
      return webinar.meetLink;
    }

    // Generate new meet link
    const meetLink = generateMeetLink();

    // Update webinar
    await prisma.webinar.update({
      where: { id: webinarId },
      data: {
        meetLink,
        autoGeneratedMeet: true,
      },
    });

    return meetLink;
  } catch (error) {
    console.error("Google Meet link generation error:", error);
    throw new ApiError(500, "Failed to generate Google Meet link");
  }
};

/**
 * Generate personalized Google Meet link for 1-to-1 sessions
 * @param {string} bookingId - Booking ID
 * @returns {Promise<string>} Generated personalized meet link
 */
export const generatePersonalizedMeetLink = async (bookingId) => {
  try {
    const booking = await prisma.webinarBooking.findUnique({
      where: { id: bookingId },
      include: { webinar: { select: { webinarType: true } } },
    });

    if (!booking) {
      throw new ApiError(404, "Booking not found");
    }

    // Only for ONE_TO_ONE webinars
    if (booking.webinar.webinarType !== "ONE_TO_ONE") {
      throw new ApiError(400, "Personalized links only available for 1-to-1 sessions");
    }

    // If already has personalized link, return it
    if (booking.personalizedMeetLink) {
      return booking.personalizedMeetLink;
    }

    // Generate new personalized meet link
    const personalizedMeetLink = generateMeetLink();

    // Update booking
    await prisma.webinarBooking.update({
      where: { id: bookingId },
      data: { personalizedMeetLink },
    });

    return personalizedMeetLink;
  } catch (error) {
    console.error("Personalized Meet link generation error:", error);
    throw new ApiError(500, "Failed to generate personalized Meet link");
  }
};

/**
 * Check if join link should be visible
 * @param {Date} scheduledAt - Webinar scheduled time
 * @param {Date} joinLinkVisibleAt - When to show link (optional)
 * @returns {boolean} Whether join link should be visible
 */
export const shouldShowJoinLink = (scheduledAt, joinLinkVisibleAt = null) => {
  const now = new Date();
  const scheduled = new Date(scheduledAt);

  // If joinLinkVisibleAt is set, use it
  if (joinLinkVisibleAt) {
    return now >= new Date(joinLinkVisibleAt);
  }

  // Default: show 10 minutes before webinar starts
  const tenMinutesBefore = new Date(scheduled.getTime() - 10 * 60 * 1000);
  return now >= tenMinutesBefore;
};
